import os
from google import genai
from google.genai import types

class FindEvilAgent:
    def __init__(self):
        print("\n" + "-"*60)
        print("[BLOCK] Agent Initialization (v0.0.5)")
        print("[ACTION] Verifying API authentication and loading hardened heuristics.")
        
        if not os.environ.get("GEMINI_API_KEY"):
            raise ValueError("[!] GEMINI_API_KEY environment variable not set.")

        self.client = genai.Client()
        self.system_instruction = """
        You are 'Project Find Evil', an autonomous DFIR agent. You analyze structured JSON telemetry generated by a rigidly controlled hardware pipeline.

        CRITICAL OPERATING DIRECTIVES (The ReAct Loop):
        1. REASON: Use `record_cognitive_process` to log your exact hypothesis.
        2. ACT: Use `execute_deterministic_pipeline` to trigger the hardware extraction and retrieve the JSON state of suspicious processes.
        3. OBSERVE: Analyze the JSON telemetry payload.
        4. REPORT: Output a highly technical, scannable final assessment of the compromised vectors based ONLY on the empirical data provided. Do not invent details.

        MANDATORY EMPIRICAL HEURISTICS (Do not violate these rules):
        - RULE 1: UCRT DEPLOYMENT IS BENIGN. If you see `api-ms-win-*` or `ucrtbase.dll` in standard deployment directories (e.g., AppData\Local\Microsoft\Teams), it is standard App-Local Deployment. Do NOT flag this as DLL Sideloading.
        - RULE 2: JIT MEMORY ARTIFACTS ARE BENIGN. The pipeline automatically filters JIT memory (null bytes). If the pipeline annotates a malfind result as a 'benign JIT compiler artifact', you MUST ignore it.
        - RULE 3: NTFS IS CASE-PRESERVING. Process capitalization anomalies (e.g., 'Explorer.EXE' vs 'explorer.exe') are strictly benign unless tied to an anomalous parent process or \Temp path.
        - RULE 4: FOCUS ON THE DROPPER. Analyze the 'cmdline' fields of the flagged processes aggressively. Hunt for LOLBins (powershell, cmd) executing encoded strings or launching from temporary paths. This is your primary vector.
        """
        print("[STATUS] [SUCCESS] Agent core initialized securely.")
        print("-" * 60)

    def create_session(self, tools_list):
        config = types.GenerateContentConfig(
            system_instruction=self.system_instruction,
            tools=tools_list,
            temperature=0.0
        )
        return self.client.chats.create(
            model='gemini-3.1-flash-lite',
            config=config
        )
